version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
        - POSTGRES_DB=tennisapp_db
        - POSTGRES_USER=sergey
        - POSTGRES_PASSWORD=sergiopostgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432'
    networks:
        - djangonetwork

  app:
    build: ./django_project
        # context: ./django_project/
        # dockerfile: ./Dockerfile
    command: python3 /tennis_app/manage.py runserver 0.0.0.0:8000
    # command: gunicorn tennis_app.wsgi:application --bind 0.0.0.0:8000
    expose:
     - '8000'
    # ports:
    #   - 8000:8000
    volumes:
      - ./tennis_app/:/home/sergey/MAI/maga/backend/works/django_project
    depends_on:
      - db
    env_file:
      - .env
    links:
       - db:db
    networks:
       - djangonetwork

networks:
    djangonetwork:
        driver: bridge

# volumes:
#   postgres_data:

#    ports:
#      - "5432:5432"
